# Generated by Django 5.0.6 on 2026-04-18 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edge_id', models.CharField(max_length=120)),
                ('source_node_id', models.CharField(max_length=120)),
                ('target_node_id', models.CharField(max_length=120)),
                ('source_handle', models.CharField(blank=True, max_length=120)),
                ('target_handle', models.CharField(blank=True, max_length=120)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='flows.flow')),
            ],
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node_id', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('start', 'Start'), ('process', 'Process'), ('decision', 'Decision'), ('message', 'Message'), ('task', 'Task'), ('wait', 'Wait'), ('end', 'End')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='flows.flow')),
            ],
        ),
        migrations.CreateModel(
            name='NodeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(max_length=80)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='flows.flow')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='flows.flownode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NodeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='flows.flow')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='flows.flownode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('assignee', models.CharField(blank=True, max_length=120)),
                ('channel', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('in_progress', 'In progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='flows.flow')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='flows.flownode')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='flows.nodenote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='flowedge',
            constraint=models.UniqueConstraint(fields=('flow', 'edge_id'), name='unique_flow_edge_id'),
        ),
        migrations.AddConstraint(
            model_name='flownode',
            constraint=models.UniqueConstraint(fields=('flow', 'node_id'), name='unique_flow_node_id'),
        ),
    ]
