# Generated by Django 5.0.6 on 2026-04-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flownode',
            name='kind',
            field=models.CharField(choices=[('start', 'Start'), ('process', 'Process'), ('decision', 'Decision'), ('message', 'Message'), ('note', 'Note'), ('task', 'Task'), ('wait', 'Wait'), ('end', 'End')], max_length=32),
        ),
    ]
